# Generated by Django 2.2.7 on 2020-01-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('year_start', models.IntegerField(blank=True, null=True, verbose_name='Year Start')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='Year End')),
                ('catalog_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catalog URL')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'db_table': 'collections',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='catalog_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Catalog URL'),
        ),
        migrations.AddField(
            model_name='record',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.Collection'),
        ),
    ]
