# Generated by Django 2.2.7 on 2019-11-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20191114_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso_639_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO 639-1'),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_639_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO 639-2'),
        ),
    ]
