# Generated by Django 2.2.7 on 2020-03-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_recordmedia_recordthumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['genre'], 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type'], 'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
        migrations.AddField(
            model_name='recordmedia',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Media File MIME Type'),
        ),
        migrations.AddField(
            model_name='recordthumbnail',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Media File MIME Type'),
        ),
        migrations.AlterField(
            model_name='record',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.Collection', verbose_name='Collection'),
        ),
    ]
