# Generated by Django 2.2.7 on 2019-11-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_record_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
        migrations.CreateModel(
            name='RecordDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Description')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_descriptions', to='repository.Record')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
                'db_table': 'record_descriptions',
            },
        ),
    ]
