# Generated by Django 2.2.7 on 2020-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20200324_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Thumbnail'),
        ),
    ]
