# Generated by Django 2.2.11 on 2020-05-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_collection_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
