# Generated by Django 2.2.7 on 2019-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20191119_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcreator',
            name='creator',
            field=models.CharField(max_length=500, verbose_name='Creator'),
        ),
    ]
