# Generated by Django 3.1.4 on 2021-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sort_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
